name: Markdown Check

on:
  pull_request:
    paths:
      - "**/*.md"
  push:
    paths:
      - "**/*.md"

jobs:
  markdown-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List markdown files
        run: find . -name "*.md" -maxdepth 6 | sort
